---

- name: Install unbound
  package:
    name:
      - ca-certificates
      - unbound
    state: present

- name: Create unbound trust anchor
  command:
    cmd: /usr/sbin/unbound-anchor -a /var/lib/unbound/root.key -4
    creates: /var/lib/unbound/root.key
  register: unbound_anchor
  failed_when: |
    unbound_anchor.rc == 0 and
    unbound_anchor.stderr is defined and
    ("Please check root.key" in unbound_anchor.stderr or
    "error:" in unbound_anchor.stderr)

- name: Configure unbound
  template:
    src: etc/unbound/unbound.j2
    dest: /etc/unbound/unbound.conf
    owner: unbound
    group: unbound
    mode: '0644'
    validate: /usr/sbin/unbound-checkconf %s
  notify: Restart unbound

- name: Set unbound as system resolver
  template:
    src: etc/resolv.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure unbound will stay as the system resolver
  file:
    path: /etc/resolv.conf
    attributes: "+i"
  register: resolv_file
  changed_when: "'i' not in resolv_file.diff.before.attributes"

- name: Start and enable unbound
  service:
    name: unbound
    enabled: true
    state: started

- name: Flush handlers
  meta: flush_handlers
