---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian10
    image: debian:10
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
